### PR TITLE
Add more than one language and change "e" to "E"

### PR DESCRIPTION
**Pull request by Bigjango13**

### CODE REVIEW

**Comment by therealsimon14** [comment]
No!!! Also E.html!!

**Comment by Bigjango13** [comment]
Why no?

**Comment by confuzled** [comment]
no .bf

**Comment by Bigjango13** [comment]
Added them.

**Comment by therealsimon14** [comment]
Yes, perfect.

**Comment by Bigjango13** [comment]
Now we just need @beiop to merge it.

**Pull request closed without merging**
